services:
  fragments:
    # yoonkyungkim/fragments:latest
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    # Define the environment inside the running container
    environment:
      # Use another environment variable, with a fallback default value
      - NODE_ENV=${NODE_ENV:-production}
      - HTPASSWD_FILE=tests/.htpasswd