services:
  fragments:
    # image: yoonkyungkim/fragments:latest
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    # Define the environment inside the running container
    environment:
      - NODE_ENV=production
      # Use another environment variable, with a fallback default value
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # # Forward any authorization variables into the container
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID
      - HTPASSWD