services:
  fragments:
    # yoonkyungkim/fragments:latest
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    # Define the environment inside the running container
    environment:
      # Use another environment variable, with a fallback default value
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=8080
      # Forward any authorization variables into the container
      - HTPASSWD_FILE
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID